### ISSUE TITLE
Deploying pretrained policy, rotation policy not working

### ISSUE THREAD

**Issue by charliehuang5** [leap-hand/LEAP_Hand_Sim#12]
When running deploy.py to deploy the pretrained policy on the hand, it seems to complete the initial grasp task ok (fingers are at least moving in the right direction -- they don't hold onto the cube very well. Then, when the rotation task starts the fingers move for a bit near that initial grasp conformation then all begin bending backwards. It seems that the pretrained policy for rotating the cube is quite sensitive to the initial state/success of the grasp. Do you have any advice on how to troubleshoot this issue? The grasp only loosely grasps onto the cube. If I apply a pressure to the cube to keep in contact with the fingers, the fingers move in a similar fashion like the simulated pretrained policy, but once that pressure is release the fingers drift backwards. I can follow up with more details on the setup.

**Comment by Lucky7Chess** [comment]
Hi Charlie,

Maybe check your real cube size relative to the simulation cube?  If it is too small, the policy will not generalize onto a different size since it was not trained on that size.   You may want to slightly tweak the PID values of the LEAP Hand code if you find that your hand has slightly different characteristics also.

**Comment by charliehuang5** [comment]
Did you also test the hand with cubes of different material and mass? I’m
using a 3D printed cube which could be smoother and lighter.

**Comment by Lucky7Chess** [comment]
I used a wooden cube.  Match the weight of your cube between sim and real.
