### ISSUE TITLE
Why are pgain and dgain so small? 

### ISSUE THREAD

**Issue by mzhmxzh** [leap-hand/LEAP_Hand_Sim#9]
In this file [LeapHandRot.yaml](https://github.com/leap-hand/LEAP_Hand_Sim/blob/ebc49e00af34b2634b1e6c746d962072fbb2f281/leapsim/cfg/task/LeapHandRot.yaml#L34), `pgain` is `3` and `dgain` is `0.1`. 

However, in this file [example.launch](https://github.com/leap-hand/LEAP_Hand_API/blob/ff8503a6cb247d18580b3d0d73fe678d0fe81f9d/ros_module/example.launch#L4) from the official API repo of the LEAP hand [LEAP_Hand_API](https://github.com/leap-hand/LEAP_Hand_API), `kP` is `800.0` and `kD` is `200.0`. 

Why are the PD parameters in the IsaacGym environment so different from those in the real world? Are there any insights in setting the appropriate PD in IsaacGym? Thanks for any help!

**Comment by Lucky7Chess** [comment]
The gains are different because the scales/units are different.   On Dynamixels see https://emanual.robotis.com/docs/en/dxl/x/xc330-m288/
for how the PID loops really work.

In Isaac the units are [N*m/rad] for stiffness and [N*m*s/rad] for damping which is an approximation of the real-world behavior.

For the result you see here, we trained in Sim and then matched the real world to be similar to the Sim by trying a few different PID gain parameters and visualizing the sim and the real world behavior.  You can also do more methodical system identification-based approach but we did not do that for this codebase.
